language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- 4
script: npm run flow_check
deploy:
  skip_cleanup: true
  provider: npm
  email: shaun.stanworth@googlemail.com
  api_key:
    secure: Q12HfJTCaL7Y5uDNH8VUiHcLwDcYzzn+azIfnd4+xXSAeR7mceYS6w4UnkMaRU3E1FlIU1sD8T7CQ6ZekMobrnvNIBt66ZwNyirNsaWRb/K77MT5Xzdhl9uSkMTAKRAE6dBVneIS4yJcIUB+nAt7MXpw78cl6Elw+D8S7E2SIf9WIV3wNPxdwpemDfqyAAuzjIzeTXjCIEcxNB2nonB2/X/BOvVWfuwqIrjg/qUUZR4uw6S2ROD+OrakxGjtpj0XgaaOamwaYZudJI5RmYdx2EuwW10KI5l7olElJENW14G1k0d2tAqThz0Zp9o/wlDBQq3l0UWh8Z2Z9rypo3qRI8HF4yzIC7lvCUeqr/Pi+nA4c0tJxhTpckCb8nj3QUfGPLyNBxC/KfBViNP4e8BTmTtFCJdCR2U5+KWo+FxzyL98Lvl5VXiUDH8G4UVCzaxYhDFcQXd2e32oNPnkx0jtprGrPk9aOnWJORlz2TNiuWgbyufkYiYr8KxwwrLU3zBSPFEF0yEZI+/bVxdvF+6bC3D5xkBFHliGMzcLCDKiYsy6l1V44njI9EPMZuw/cspWV4PYGYOdbYcTk13+3kc+OUxwQJ9G30s15w7oQxB9mucS/qHZ2pgn64aPZTyPMG7bhNM1Nvatf+qfi5bjtDYNL7PXvycWzDPWILYZSRp0UVA=
  on:
    repo: shauns/ff-identity-tools
    branch: master
