language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - 7
script: npm run flow_check
deploy:
  skip_cleanup: true
  provider: npm
  email: shaun.stanworth@googlemail.com
  api_key:
    secure: IzcLZY+jXOkE8ijRsJlFebM9Yp2/00j2oj3hZK7tBX5XMSdbje6kQBWDaSzKG9urJydiNz+cyOtiwVTvJuOT/rVj0RI7+Ys7/H7V56x1tLNtpZaGVXCUr11/bFoRmMREXDNTBqvHQmmWpHPxacrHRcfM5VLrVMhwTTywN/mQ+RDYFdgugsF2/V7VP93vA6OVlKcJXBFffnHWu+aoJ/gQ9d6sqfKKgVyOZAMo/M5MAPubxfuf7et4jwwot421zLYEfDjHR0yNLhFK/CNDxQsvXvifaMnK+s88Vih7RRJa1onBOZn76TAGuhEY9seYqBsGqpmHyx0MANKqY+BTL3COi8bUjT6grE+mn/ItlmXJacMxrfG3kGAuOvH1TQwqqKy5/8zozm5WPwggOWMpjpK2fEnbpnykFIAT8WPTh6vAAX5vhPkeqll2r6YA8sgayZXUlJOkEgD3HTl2Ez758BtG1J/9yCjUewMhuJ2ulcjATZEhHgBWZpo2hf5ystIElqgZeli+eQf6jpz81qwevp62ApVbZ4790mHVg3r0dT7TSVOGjEfC+G59ooc2V61lBrGsElj8R3XwA1u2lx9fgtQ/ZeNSMFoPSaQFRvdNbqRh/ACEZP2Q7LGSIfGq2NfRYm/RXnyhdZLMmvGvUXa5hNE0ZpLJ1ZEiZyzn9BYTvrjYnG8=
  on:
    repo: shauns/ff-identity-tools
    branch: master
